### ISSUE TITLE
Suggestion minor feature: postParagraph

### ISSUE THREAD

**Issue by Ezbob** [jakobandersen/mod#1]
Currently I cannot find any way to post regular paragraphs to the summary file. This feature would help in making commentary in the summary pdf.

**Comment by jakobandersen** [comment]
Do you mean inserting a `\paragraph{Title}` or inserting a piece of arbitrary Latex code? At the moment there are only short-hands for chapter down to subsubsection. There is no simple way of inserting arbitrary code, but using a few undocumented features it is possible :-):

``` python
commentNum = 0 
def makeComment(s):
    global commentNum
    texFilename = "out/comment_%d.tex" % commentNum
    commentNum += 1
    with open(texFilename, 'w') as f:
        f.write(s)
        f.write('\n')
    post('summaryInput "%s"' % texFilename)

postSection("Stuff")
makeComment("hello")

postSection("More Stuff")
makeComment("hello again")
```

The `post` function inserts a command for the post-processor, as a Bash command (so don't do `post("rm -rf /")`). A pre-defined post-function is `summaryInput f` which inserts `\input{f}` into the summary.

When I find time I will try to write more documentation for the post-processor.

**Comment by Ezbob** [comment]
Sounds good. I was thinking about inserting pieces of Latex code into the summary pdf. Thanks for your time.

**Comment by jakobandersen** [comment]
This can be done with [``post.summaryRaw()``](https://jakobandersen.github.io/mod/pymod/Post.html#mod.post.summaryRaw) (since November 2022, I forgot to close this):
```py
post.summaryRaw(R"\paragraph{blah}")
```
