### ISSUE TITLE
MacOSx package pkg-config missing

### ISSUE THREAD

**Issue by aehrlich1** [jakobandersen/mod#16]
During the installation process with a MAC silicon I got the error 'package pkg-config missing'.
'brew install pkg-config' fixed this.

**Comment by jakobandersen** [comment]
Thanks for reporting. Unfortunately I don't have access to similar system to test on, but I have added ``pkg-config`` to ``Brewfile``, on the ``develop`` branch.
If you have time to test it and there still is a problem, you are most welcome to reopen the issue.
