### ISSUE TITLE
Live playground examples with `include()` are broken

### ISSUE THREAD

**Issue by hbsmith** [jakobandersen/mod#17]
Hi @jakobandersen --

Wanted to let you know that I was trying to use the live playground, and noticed that all the examples with `include()` are broken. It seems like your internal file structure must have changed.

e.g. https://cheminf-live.imada.sdu.dk/mod/?example=000_basics__051_fileInclusion.py or any of the examples here https://jakobandersen.github.io/mod/examples/020_dg.html

Thanks!

**Comment by jakobandersen** [comment]
Thanks for reporting, the server did not know how to handle the new examples structure. It should be fixed now.
