### ISSUE TITLE
Not able to compile mod v.0.7.0

### ISSUE THREAD

**Issue by mrgreuter** [jakobandersen/mod#3]
I am not able to compile mod, even though I (think :) I meet all the requirements (boost, perm_group, ... ) !
~~~
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:30:35: error: no type named 'perm' in 'class std::vector<int>'
  using perm = typename Alloc::perm;
                                   ^
In file included from /home/vagrant/local/include/boost/concept/assert.hpp:35:0,
                 from /home/vagrant/local/include/boost/property_map/property_map.hpp:19,
                 from /home/vagrant/local/include/boost/graph/adjacency_list.hpp:28,
                 from ../src/jla_boost/graph/EdgeIndexedAdjacencyList.hpp:4,
                 from ../src/mod/lib/Graph/GraphDecl.h:4,
                 from ../src/mod/lib/Graph/Single.h:7,
                 from mod/graph/Automorphism.cpp:4:
/home/vagrant/local/include/boost/concept/detail/general.hpp:71:5: error: no type named 'perm' in 'class std::vector<int>'
     &::boost::concepts::requirement_<ModelFnPtr>::failed>    \
     ^
/home/vagrant/local/include/boost/concept/assert.hpp:43:5: note: in expansion of macro 'BOOST_CONCEPT_ASSERT_FN'
     BOOST_CONCEPT_ASSERT_FN(void(*)ModelInParens)
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:31:2: note: in expansion of macro 'BOOST_CONCEPT_ASSERT'
  BOOST_CONCEPT_ASSERT((Permutation<perm>));
  ^
In file included from ../src/mod/lib/Graph/Single.h:12:0,
                 from mod/graph/Automorphism.cpp:4:
/home/vagrant/local/include/perm_group/group/generated.hpp: In instantiation of 'struct perm_group::generated_group<std::vector<int> >':
mod/graph/Automorphism.cpp:20:34:   required from here
/home/vagrant/local/include/perm_group/group/generated.hpp:33:39: error: no type named 'perm' in 'using allocator = class std::vector<int> {aka class std::vector<int>}'
  using perm = typename allocator::perm;
                                       ^
In file included from ../src/mod/lib/Graph/Single.h:12:0,
                 from mod/graph/Automorphism.cpp:4:
/home/vagrant/local/include/perm_group/group/generated.hpp:110:39: error: no type named 'perm' in 'class std::vector<int>'
  PtrContainerToPermProxy<Store, perm> generators() const {
                                       ^~~~~~~~~~
mod/graph/Automorphism.cpp: In member function 'mod::graph::Graph::Vertex mod::graph::Graph::Aut::operator[](mod::graph::Graph::Vertex) const':
mod/graph/Automorphism.cpp:20:18: error: 'generators' was not declared in this scope
  const auto &p = generators(group)[i];
                  ^~~~~~~~~~
mod/graph/Automorphism.cpp:20:18: note: suggested alternative: 'operator='
  const auto &p = generators(group)[i];
                  ^~~~~~~~~~
                  operator=
mod/graph/Automorphism.cpp: In function 'std::ostream& mod::graph::operator<<(std::ostream&, const mod::graph::Graph::Aut&)':
mod/graph/Automorphism.cpp:27:18: error: 'generators' was not declared in this scope
  const auto &p = generators(group)[a.i];
                  ^~~~~~~~~~
mod/graph/Automorphism.cpp:27:18: note: suggested alternative: 'operator<'
  const auto &p = generators(group)[a.i];
                  ^~~~~~~~~~
                  operator<
mod/graph/Automorphism.cpp: In member function 'mod::graph::Graph::AutGroup::Gens::iterator mod::graph::Graph::AutGroup::Gens::end() const':
mod/graph/Automorphism.cpp:45:37: error: 'generators' was not declared in this scope
  return iterator(g, lt, withStereo, generators(group).size());
                                     ^~~~~~~~~~
mod/graph/Automorphism.cpp:45:37: note: suggested alternative: 'iterator'
  return iterator(g, lt, withStereo, generators(group).size());
                                     ^~~~~~~~~~
                                     iterator
In file included from /home/vagrant/local/include/perm_group/group/generated.hpp:4:0,
                 from ../src/mod/lib/Graph/Single.h:12,
                 from mod/graph/Automorphism.cpp:4:
/home/vagrant/local/include/perm_group/allocator/allocator.hpp: In instantiation of 'perm_group::Allocator<Alloc>::~Allocator() [with Alloc = std::vector<int>]':
/home/vagrant/local/include/boost/concept/detail/general.hpp:39:28:   required from 'static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = perm_group::Allocator<std::vector<int> >]'
/home/vagrant/local/include/perm_group/group/generated.hpp:28:2:   required from 'struct perm_group::generated_group<std::vector<int> >'
mod/graph/Automorphism.cpp:20:34:   required from here
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:71:26: error: 'const class std::vector<int>' has no member named 'degree'
   std::size_t n = cAlloc.degree();
                   ~~~~~~~^~~~~~
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:73:23: error: 'class std::vector<int>' has no member named 'make'
   pointer ptr = alloc.make();
                 ~~~~~~^~~~
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:74:28: error: 'class std::vector<int>' has no member named 'make_identity'
   const_pointer id = alloc.make_identity();
                      ~~~~~~^~~~~~~~~~~~~
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:75:9: error: 'class std::vector<int>' has no member named 'release'; did you mean 'reserve'?
   alloc.release(ptr);
   ~~~~~~^~~~~~~
   reserve
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:76:9: error: 'class std::vector<int>' has no member named 'release'; did you mean 'reserve'?
   alloc.release(id);
   ~~~~~~^~~~~~~
   reserve
/home/vagrant/local/include/perm_group/allocator/allocator.hpp:80:29: error: 'class std::vector<int>' has no member named 'copy'
   const_pointer cpy = alloc.copy(p);
                       ~~~~~~^~~~
make[1]: *** [Makefile:1729: mod/graph/libmod_la-Automorphism.lo] Error 1
make[1]: Leaving directory '/home/vagrant/mod-v0.7.0/src'
make: *** [Makefile:489: all-recursive] Error 1
~~~
Any hints :) ?

**Comment by jnyrup** [comment]
If it is of any help, I got the same error:
* Linux Mint 19.1 (Ubuntu 18.04)
* GCC 7.3.0
* Boost 1.69.0
* downloaded master of mod, perm_group and graph_cannon

<pre>libtool: compile:  g++ -DHAVE_CONFIG_H -I../src -I../src -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_SYSTEM_NO_DEPRECATED -I/home/jonyr09/Downloads/boost_1_69_0/install/include -I/usr/include/openbabel-2.0 -I/usr/include/python3.6m -I/usr/local/include -I/usr/local/lib/include -std=c++14 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-comment -Wno-maybe-uninitialized -Wno-deprecated-declarations -g -O3 -MT mod/graph/libmod_la-GraphInterface.lo -MD -MP -MF mod/graph/.deps/libmod_la-GraphInterface.Tpo -c mod/graph/GraphInterface.cpp  -fPIC -DPIC -o mod/graph/.libs/libmod_la-GraphInterface.o
In file included from <b>/usr/local/include/perm_group/group/generated.hpp:4:0</b>,
                 from <b>../src/mod/lib/Graph/Single.h:12</b>,
                 from <b>mod/graph/Automorphism.cpp:4</b>:
/usr/local/include/perm_group/allocator/allocator.hpp: In instantiation of ‘<b>struct perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;</b>’:
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:32:62:</b>   required by substitution of ‘<b>template&lt;class Model&gt; boost::concepts::detail::yes boost::concepts::detail::has_constraints_(Model*, boost::concepts::detail::wrap_constraints&lt;Model, (&amp; Model:: constraints)&gt;*) [with Model = perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;]</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:42:5:</b>   required from ‘<b>const bool boost::concepts::not_satisfied&lt;perm_group::Allocator&lt;std::vector&lt;int&gt; &gt; &gt;::value</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:45:51:</b>   required from ‘<b>struct boost::concepts::not_satisfied&lt;perm_group::Allocator&lt;std::vector&lt;int&gt; &gt; &gt;</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/general.hpp:51:8:</b>   required from ‘<b>struct boost::concepts::requirement_&lt;void (*)(perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;)&gt;</b>’
<b>/usr/local/include/perm_group/group/generated.hpp:28:2:</b>   required from ‘<b>struct perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;</b>’
<b>mod/graph/Automorphism.cpp:20:34:</b>   required from here
<b>/usr/local/include/perm_group/allocator/allocator.hpp:30:35:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
  using perm = typename Alloc::perm<font color="#FF0000"><b>;</b></font>
                                   <font color="#FF0000"><b>^</b></font>
In file included from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/assert.hpp:35:0</b>,
                 from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/property_map/property_map.hpp:19</b>,
                 from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/graph/adjacency_list.hpp:28</b>,
                 from <b>../src/jla_boost/graph/EdgeIndexedAdjacencyList.hpp:4</b>,
                 from <b>../src/mod/lib/Graph/GraphDecl.h:4</b>,
                 from <b>../src/mod/lib/Graph/Single.h:7</b>,
                 from <b>mod/graph/Automorphism.cpp:4</b>:
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/general.hpp:71:5:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
     <font color="#FF0000"><b>&amp;</b></font>::boost::concepts::requirement_&lt;ModelFnPtr&gt;::failed&gt;    \
     <font color="#FF0000"><b>^</b></font>
In file included from <b>../src/mod/lib/Graph/Single.h:12:0</b>,
                 from <b>mod/graph/Automorphism.cpp:4</b>:
/usr/local/include/perm_group/group/generated.hpp: In instantiation of ‘<b>struct perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;</b>’:
<b>mod/graph/Automorphism.cpp:20:34:</b>   required from here
<b>/usr/local/include/perm_group/group/generated.hpp:33:39:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>using allocator = class std::vector&lt;int&gt; {aka class std::vector&lt;int&gt;}</b>’
  using perm = typename allocator::perm<font color="#FF0000"><b>;</b></font>
                                       <font color="#FF0000"><b>^</b></font>
In file included from <b>../src/mod/lib/Graph/Single.h:12:0</b>,
                 from <b>mod/graph/Automorphism.cpp:4</b>:
<b>/usr/local/include/perm_group/group/generated.hpp:110:39:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
  PtrContainerToPermProxy&lt;Store, perm&gt; <font color="#FF0000"><b>generators</b></font>() const {
                                       <font color="#FF0000"><b>^~~~~~~~~~</b></font>
<b>mod/graph/Automorphism.cpp:</b> In member function ‘<b>mod::graph::Graph::Vertex mod::graph::Graph::Aut::operator[](mod::graph::Graph::Vertex) const</b>’:
<b>mod/graph/Automorphism.cpp:20:18:</b> <font color="#FF0000"><b>error: </b></font>‘<b>generators</b>’ was not declared in this scope
  const auto &amp;p = <font color="#FF0000"><b>generators</b></font>(group)[i];
                  <font color="#FF0000"><b>^~~~~~~~~~</b></font>
<b>mod/graph/Automorphism.cpp:20:18:</b> <font color="#00FFFF"><b>note: </b></font>suggested alternative: ‘<b>operator=</b>’
  const auto &amp;p = <font color="#00FFFF"><b>generators</b></font>(group)[i];
                  <font color="#00FFFF"><b>^~~~~~~~~~</b></font>
                  <font color="#00CD00">operator=</font>
<b>mod/graph/Automorphism.cpp:</b> In function ‘<b>std::ostream&amp; mod::graph::operator&lt;&lt;(std::ostream&amp;, const mod::graph::Graph::Aut&amp;)</b>’:
<b>mod/graph/Automorphism.cpp:27:18:</b> <font color="#FF0000"><b>error: </b></font>‘<b>generators</b>’ was not declared in this scope
  const auto &amp;p = <font color="#FF0000"><b>generators</b></font>(group)[a.i];
                  <font color="#FF0000"><b>^~~~~~~~~~</b></font>
<b>mod/graph/Automorphism.cpp:27:18:</b> <font color="#00FFFF"><b>note: </b></font>suggested alternative: ‘<b>operator&lt;</b>’
  const auto &amp;p = <font color="#00FFFF"><b>generators</b></font>(group)[a.i];
                  <font color="#00FFFF"><b>^~~~~~~~~~</b></font>
                  <font color="#00CD00">operator&lt;</font>
<b>mod/graph/Automorphism.cpp:</b> In member function ‘<b>mod::graph::Graph::AutGroup::Gens::iterator mod::graph::Graph::AutGroup::Gens::end() const</b>’:
<b>mod/graph/Automorphism.cpp:45:37:</b> <font color="#FF0000"><b>error: </b></font>‘<b>generators</b>’ was not declared in this scope
  return iterator(g, lt, withStereo, <font color="#FF0000"><b>generators</b></font>(group).size());
                                     <font color="#FF0000"><b>^~~~~~~~~~</b></font>
<b>mod/graph/Automorphism.cpp:45:37:</b> <font color="#00FFFF"><b>note: </b></font>suggested alternative: ‘<b>iterator</b>’
  return iterator(g, lt, withStereo, <font color="#00FFFF"><b>generators</b></font>(group).size());
                                     <font color="#00FFFF"><b>^~~~~~~~~~</b></font>
                                     <font color="#00CD00">iterator</font>
In file included from <b>/usr/local/include/perm_group/group/generated.hpp:4:0</b>,
                 from <b>../src/mod/lib/Graph/Single.h:12</b>,
                 from <b>mod/graph/Automorphism.cpp:4</b>:
/usr/local/include/perm_group/allocator/allocator.hpp: In instantiation of ‘<b>perm_group::Allocator&lt;Alloc&gt;::~Allocator() [with Alloc = std::vector&lt;int&gt;]</b>’:
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/general.hpp:39:28:</b>   required from ‘<b>static void boost::concepts::requirement&lt;boost::concepts::failed************ Model::************&gt;::failed() [with Model = perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;]</b>’
<b>/usr/local/include/perm_group/group/generated.hpp:28:2:</b>   required from ‘<b>struct perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;</b>’
<b>mod/graph/Automorphism.cpp:20:34:</b>   required from here
<b>/usr/local/include/perm_group/allocator/allocator.hpp:71:26:</b> <font color="#FF0000"><b>error: </b></font>‘<b>const class std::vector&lt;int&gt;</b>’ has no member named ‘<b>degree</b>’
   std::size_t n = <font color="#FF0000"><b>cAlloc.degree</b></font>();
                   <font color="#FF0000"><b>~~~~~~~^~~~~~</b></font>
<b>/usr/local/include/perm_group/allocator/allocator.hpp:73:23:</b> <font color="#FF0000"><b>error: </b></font>‘<b>class std::vector&lt;int&gt;</b>’ has no member named ‘<b>make</b>’
   pointer ptr = <font color="#FF0000"><b>alloc.make</b></font>();
                 <font color="#FF0000"><b>~~~~~~^~~~</b></font>
<b>/usr/local/include/perm_group/allocator/allocator.hpp:74:28:</b> <font color="#FF0000"><b>error: </b></font>‘<b>class std::vector&lt;int&gt;</b>’ has no member named ‘<b>make_identity</b>’
   const_pointer id = <font color="#FF0000"><b>alloc.make_identity</b></font>();
                      <font color="#FF0000"><b>~~~~~~^~~~~~~~~~~~~</b></font>
<b>/usr/local/include/perm_group/allocator/allocator.hpp:75:9:</b> <font color="#FF0000"><b>error: </b></font>‘<b>class std::vector&lt;int&gt;</b>’ has no member named ‘<b>release</b>’; did you mean ‘<b>reserve</b>’?
   <font color="#FF0000"><b>alloc.release</b></font>(ptr);
   <font color="#FF0000"><b>~~~~~~^~~~~~~</b></font>
   <font color="#00CD00">reserve</font>
<b>/usr/local/include/perm_group/allocator/allocator.hpp:76:9:</b> <font color="#FF0000"><b>error: </b></font>‘<b>class std::vector&lt;int&gt;</b>’ has no member named ‘<b>release</b>’; did you mean ‘<b>reserve</b>’?
   <font color="#FF0000"><b>alloc.release</b></font>(id);
   <font color="#FF0000"><b>~~~~~~^~~~~~~</b></font>
   <font color="#00CD00">reserve</font>
<b>/usr/local/include/perm_group/allocator/allocator.hpp:80:29:</b> <font color="#FF0000"><b>error: </b></font>‘<b>class std::vector&lt;int&gt;</b>’ has no member named ‘<b>copy</b>’
   const_pointer cpy = <font color="#FF0000"><b>alloc.copy</b></font>(p);
                       <font color="#FF0000"><b>~~~~~~^~~~</b></font>
Makefile:1730: recipe for target &apos;mod/graph/libmod_la-Automorphism.lo&apos; failed
make[1]: *** [mod/graph/libmod_la-Automorphism.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from <b>/usr/local/include/perm_group/group/generated.hpp:4:0</b>,
                 from <b>../src/mod/lib/Graph/Single.h:12</b>,
                 from <b>mod/graph/Graph.cpp:8</b>:
/usr/local/include/perm_group/allocator/allocator.hpp: In instantiation of ‘<b>struct perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;</b>’:
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:32:62:</b>   required by substitution of ‘<b>template&lt;class Model&gt; boost::concepts::detail::yes boost::concepts::detail::has_constraints_(Model*, boost::concepts::detail::wrap_constraints&lt;Model, (&amp; Model:: constraints)&gt;*) [with Model = perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;]</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:42:5:</b>   required from ‘<b>const bool boost::concepts::not_satisfied&lt;perm_group::Allocator&lt;std::vector&lt;int&gt; &gt; &gt;::value</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/has_constraints.hpp:45:51:</b>   required from ‘<b>struct boost::concepts::not_satisfied&lt;perm_group::Allocator&lt;std::vector&lt;int&gt; &gt; &gt;</b>’
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/general.hpp:51:8:</b>   required from ‘<b>struct boost::concepts::requirement_&lt;void (*)(perm_group::Allocator&lt;std::vector&lt;int&gt; &gt;)&gt;</b>’
<b>/usr/local/include/perm_group/group/generated.hpp:28:2:</b>   required from ‘<b>struct perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;</b>’
<b>/usr/include/c++/7/bits/unique_ptr.h:76:22:</b>   required from ‘<b>void std::default_delete&lt;_Tp&gt;::operator()(_Tp*) const [with _Tp = const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;]</b>’
<b>/usr/include/c++/7/bits/unique_ptr.h:268:17:</b>   required from ‘<b>std::unique_ptr&lt;_Tp, _Dp&gt;::~unique_ptr() [with _Tp = const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;; _Dp = std::default_delete&lt;const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt; &gt;]</b>’
<b>../src/mod/lib/Graph/Single.h:36:2:</b>   required from ‘<b>typename std::_MakeUniq&lt;_Tp&gt;::__single_object std::make_unique(_Args&amp;&amp; ...) [with _Tp = mod::lib::Graph::Single; _Args = {mod::lib::Graph::Single}; typename std::_MakeUniq&lt;_Tp&gt;::__single_object = std::unique_ptr&lt;mod::lib::Graph::Single&gt;]</b>’
<b>mod/graph/Graph.cpp:187:101:</b>   required from here
<b>/usr/local/include/perm_group/allocator/allocator.hpp:30:35:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
  using perm = typename Alloc::perm<font color="#FF0000"><b>;</b></font>
                                   <font color="#FF0000"><b>^</b></font>
In file included from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/assert.hpp:35:0</b>,
                 from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/property_map/property_map.hpp:19</b>,
                 from <b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/graph/adjacency_list.hpp:28</b>,
                 from <b>../src/jla_boost/graph/EdgeIndexedAdjacencyList.hpp:4</b>,
                 from <b>../src/mod/lib/Graph/GraphDecl.h:4</b>,
                 from <b>../src/mod/lib/Graph/Single.h:7</b>,
                 from <b>mod/graph/Graph.cpp:8</b>:
<b>/home/jonyr09/Downloads/boost_1_69_0/install/include/boost/concept/detail/general.hpp:71:5:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
     <font color="#FF0000"><b>&amp;</b></font>::boost::concepts::requirement_&lt;ModelFnPtr&gt;::failed&gt;    \
     <font color="#FF0000"><b>^</b></font>
In file included from <b>../src/mod/lib/Graph/Single.h:12:0</b>,
                 from <b>mod/graph/Graph.cpp:8</b>:
/usr/local/include/perm_group/group/generated.hpp: In instantiation of ‘<b>struct perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;</b>’:
<b>/usr/include/c++/7/bits/unique_ptr.h:76:22:</b>   required from ‘<b>void std::default_delete&lt;_Tp&gt;::operator()(_Tp*) const [with _Tp = const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;]</b>’
<b>/usr/include/c++/7/bits/unique_ptr.h:268:17:</b>   required from ‘<b>std::unique_ptr&lt;_Tp, _Dp&gt;::~unique_ptr() [with _Tp = const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt;; _Dp = std::default_delete&lt;const perm_group::generated_group&lt;std::vector&lt;int&gt; &gt; &gt;]</b>’
<b>../src/mod/lib/Graph/Single.h:36:2:</b>   required from ‘<b>typename std::_MakeUniq&lt;_Tp&gt;::__single_object std::make_unique(_Args&amp;&amp; ...) [with _Tp = mod::lib::Graph::Single; _Args = {mod::lib::Graph::Single}; typename std::_MakeUniq&lt;_Tp&gt;::__single_object = std::unique_ptr&lt;mod::lib::Graph::Single&gt;]</b>’
<b>mod/graph/Graph.cpp:187:101:</b>   required from here
<b>/usr/local/include/perm_group/group/generated.hpp:33:39:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>using allocator = class std::vector&lt;int&gt; {aka class std::vector&lt;int&gt;}</b>’
  using perm = typename allocator::perm<font color="#FF0000"><b>;</b></font>
                                       <font color="#FF0000"><b>^</b></font>
In file included from <b>../src/mod/lib/Graph/Single.h:12:0</b>,
                 from <b>mod/graph/Graph.cpp:8</b>:
<b>/usr/local/include/perm_group/group/generated.hpp:110:39:</b> <font color="#FF0000"><b>error: </b></font>no type named ‘<b>perm</b>’ in ‘<b>class std::vector&lt;int&gt;</b>’
  PtrContainerToPermProxy&lt;Store, perm&gt; <font color="#FF0000"><b>generators</b></font>() const {
                                       <font color="#FF0000"><b>^~~~~~~~~~</b></font>
Makefile:1737: recipe for target &apos;mod/graph/libmod_la-Graph.lo&apos; failed
make[1]: *** [mod/graph/libmod_la-Graph.lo] Error 1
mv -f mod/graph/.deps/libmod_la-GraphInterface.Tpo mod/graph/.deps/libmod_la-GraphInterface.Plo
mv -f jla_boost/test/.deps/libmod_la-vf2.Tpo jla_boost/test/.deps/libmod_la-vf2.Plo
make[1]: Leaving directory &apos;/home/jonyr09/git/mod/src&apos;
Makefile:490: recipe for target &apos;all-recursive&apos; failed
make: *** [all-recursive] Error 1
</pre>

**Comment by jakobandersen** [comment]
Thanks for reporting. This is version problem as I haven't released a new MØD version since v0.3 of PermGroup and GraphCanon. If you downgrade to v0.2 of those two libraries, then it should work.

**Comment by mrgreuter** [comment]
Ok, I can confirm that with PermGroup and GraphCanon version 0.2 it compiles successfully! Thanks.

**Comment by jakobandersen** [comment]
While I forgot to write it in the change log, the 0.8 version should now compile with v0.3 of GraphCanon and PermGroup.

**Comment by jakobandersen** [comment]
I guess this should have been closed earlier. However, note that in v0.9 the GraphCanon dependency is now a Git submodule (which again has PermGroup as a submodule), so getting the right version is as simple as ``git submodule update --init --recursive``.
