### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Ranadogan** [jakobandersen/mod#6]
I have a Windows operating system and I have installed Virtual Box with Linux Mint 19.3.cinnamon. I followed all instructuons from your installation page and from here: https://github.com/cartilage-ftw/looping-structure-from-scratch/blob/master/test/mod/MOD_getting_started.md
I am still getting these errors:

`! Missing \endcsname inserted.
<to be read again> 
                   \unhbox 
<*> ...�stü/mod/libs/post_mod/share/mod/mod}\dump
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on commonPreamble.log.
libs/post_mod/CMakeFiles/commonPreamble.dir/build.make:58: recipe for target 'libs/post_mod/CMakeFiles/commonPreamble' failed
make[2]: *** [libs/post_mod/CMakeFiles/commonPreamble] Error 1
CMakeFiles/Makefile2:559: recipe for target 'libs/post_mod/CMakeFiles/commonPreamble.dir/all' failed
make[1]: *** [libs/post_mod/CMakeFiles/commonPreamble.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2`

Any ideas on how to fix this? Thank you!
`

**Comment by jakobandersen** [comment]
That looks quite odd. Can you attach the ``commonPreamble.log`` file it mentions, or send it to me?

**Comment by Ranadogan** [comment]
[commonPreamble.log](https://github.com/jakobandersen/mod/files/4688317/commonPreamble.log)

**Comment by jakobandersen** [comment]
Hmm, not sure what is going on with pdflatex here. It looks like you have non-ascii characters in your filenames, which may be why it gets confused. My only idea right now is to try in a different folder where there are only ascii characters in the full path.

**Comment by jakobandersen** [comment]
Closing for now, not sure this can be fixed from the side of MØD. Feel free to reopen if there are any updates.
