### ISSUE TITLE
Rule Printing does not show one oxygen atom (although declared and used in rule)

### ISSUE THREAD

**Issue by cartilage-ftw** [jakobandersen/mod#7]
![Problem with rule printing](https://i.imgur.com/JjtbSr4.png)
There are 2 oxygens which have been defined and used in the rule but when I print the rule it shows only one of them. It should be emphasized that when the rule is applied, the output is exactly what is expected, no inconsistencies there.
```python
ketoEnolisation = [ruleGMLString("""rule [
    ruleID "Keto-enol migration twice" # to avoid enols (and tautomers in general)
    left[
        edge [ source 1 target 2 label "=" ]

        edge [ source 3 target 4 label "-" ]
        edge [ source 3 target 6 label "-" ]
    ]
    context [
        node [ id 1 label "C" ]
        node [ id 2 label "O" ]

        node [ id 3 label "C" ]
        node [ id 4 label "O" ]
        node [ id 5 label "H" ]
        node [ id 6 label "H" ]
        edge [ source 4 target 5 label "-" ]
        edge [ source 1 target 3 label "-" ]
    ]
    right [
        edge [ source 1 target 4 label "-" ]
        edge [ source 1 target 6 label "-" ]
        edge [ source 2 target 3 label "=" ]
    ]
]
""")]
```
Please see if you can reproduce this problem.

**Comment by jakobandersen** [comment]
Both oxygens are printed, but Open Babel (which generates the coordinates) decided they should have the same position, leading to this rather uninformative picture. If you print the rule with a ``GraphPrinter`` with ``withIndex = True`` you can see two numbers floating near the O.
Unfortunately this is not something I can easily fix in MØD.
