### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by cartilage-ftw** [jakobandersen/mod#9]
I had trouble particularly while reading a .txt file and then loading graphs using smiles(). I tried to debug a bit and will tell you what I noticed. I was trying to do something along the lines of
```python
with open("not_matching.txt") as nm:
	list_structs = nm.readlines()
	for line in list_structs:
		print("This block was executed once!")
		mol_smiles = line.replace("\n", "")
		mol_to_search = smiles(mol_smiles, name="Mol to Search")
```
and received the error
```bash
Traceback (most recent call last):
  File "out/input", line 56, in <module>
    include("find_missing.py")
  File "out/input", line 46, in include
    exec(code, globals())
  File "find_missing.py", line 42, in <module>
    mol_to_search = smiles(mol_smiles, name="Mol to Search")
TypeError: 'str' object is not callable
```
I can't seem to find any syntactical errors. A few things I noted.

* I did not get this error when I commented out the ```with open("not_matching.txt") as nm:``` block and did just
```python
for mol_smiles in list_structs:
	mol_to_search = smiles(mol_smiles, "struct to search")
```
* I got the same stack trace when I kept the block for reading the .txt and tried to load using smiles() outside it (I was thinking that internally some "input" stream that the file I/O uses was being overriden by some code in libpymod), i.e., the following block
```python
with open("not_matching.txt") as nm:
	list_structs = nm.readlines()
	for i in range(len(list_structs)):
		list_structs[i] = list_structs[i].replace("\n", "")

for mol_smiles in list_structs:
	mol_to_search = smiles(mol_smiles, "struct to search")
```
gave the same error. The solutions on stackoverflow haven't helped.

**Comment by jakobandersen** [comment]
It could look like you assign a string to the name ``smiles`` somewhere earlier. In that case, in order to get the MØD function you will need to fully qualify it: ``g = mod.smiles(aSmilesString, "name")``.

**Comment by cartilage-ftw** [comment]
Yes I checked and it seems that I did, although inside a local context (inside a loop) I think (which I thought would be destroyed once the block completed execution).
Sorry this wasn't anything to do with MØD.
